### PR TITLE
fix 'exsit' to 'exist'

### PR DESCRIPTION
**Pull request by GuodongH**
the exist filed is in the ctx, fix this spell error to prevent other errors

### CODE REVIEW

**Comment by alcfy** [comment]
Can you check the frontend where it calls this endpoint? Since it was working the frontend may have this typo as well

**Comment by GuodongH** [comment]
> Can you check the frontend where it calls this endpoint? Since it was working the frontend may have this typo as well

I search the whole project, only these 3 files use the spell wrong word 'exsit'.

**Comment by ludiw823** [comment]
Actually, this router is only used in return-portal, in `return-portal/client/pages/Confirmation/IdentifyApp2.js`, function `checkReturnsFromDB` in line 318

**Comment by alcfy** [comment]
Does the check return from dB function have this typo?

**Pull request merged**
